apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
  namespace: backstage
  # for minikube
  # labels:
  #  type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: backstage
    name: postgres-storage-claim
  gcePersistentDisk:
    pdName: backstage-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  # for minikube
  # hostPath:
  #  path: '/mnt/data'

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
  namespace: backstage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
